#!/usr/bin/env python3
# extract_chan_tuning_2069rev4.py
#
# Per-channel radio tuning dump for the DSL-3580L (radio 2069 *rev4*).
#
# The DSL is radio 2069 rev4, so the rev4 table (58 u16/entry) is authoritative;
# the rev>=16 table would be the wrong one for this board.
# Entry layout:
#     u16[0] = channel number
#     u16[1] = center frequency (MHz)
#     u16[2..57] = 56 radio raw values consumed by
#

import argparse, os, struct, hashlib
from elftools.elf.elffile import ELFFile

SYM = 'chan_tuning_2069rev4'
U16_PER_ENTRY = 0x3a            # 58
ENTRY_BYTES = U16_PER_ENTRY * 2  # 116
MAX_ENTRIES = 0x4d              # 77

# off -> radio reg, cluster1, offsets 4..92.
CLUSTER1_MAP = {
    4: 0x08e0,  6: 0x08e1,  8: 0x08dd, 10: 0x08dc, 12: 0x08e6, 14: 0x08e7,
   16: 0x08c4, 18: 0x08c5, 20: 0x08e5, 22: 0x08eb, 24: 0x08d6, 26: 0x0113,
   28: 0x08db, 30: 0x08da, 32: 0x08d7, 34: 0x0885, 36: 0x0886, 38: 0x0887,
   40: 0x08d9, 42: 0x08d8, 44: 0x08c9, 46: 0x08ca, 48: 0x08cc, 50: 0x08c7,
   52: 0x08c8, 54: 0x0892, 56: 0x0894, 58: 0x0895, 60: 0x0896, 62: 0x0897,
   64: 0x0899, 66: 0x089a, 68: 0x089b, 70: 0x089c, 72: 0x0112, 74: 0x0629,
   76: 0x065b, 78: 0x065e, 80: 0x0668, 82: 0x011a, 84: 0x011b, 86: 0x0719,
   88: 0x0630, 90: 0x065c, 92: 0x0662,
}
TAIL_OFFS = list(range(94, ENTRY_BYTES, 2))   # 94..114, rev4-only, regs = TODO

FIVE_G_MIN_FREQ = 5170          # channel 34; "5 GHz from ch 34 up"


def read_table(elf_path):
    with open(elf_path, 'rb') as f:
        sha = hashlib.sha256(f.read()).hexdigest()
    elf = ELFFile(open(elf_path, 'rb'))
    st = elf.get_section_by_name('.symtab')
    sym = next((s for s in st.iter_symbols() if s.name == SYM), None)
    if sym is None:
        raise SystemExit(f"{SYM} not found in {elf_path}")
    shndx, val, size = sym['st_shndx'], sym['st_value'], sym['st_size']
    data = list(elf.iter_sections())[shndx].data()[val:val + size]
    n = min(size // ENTRY_BYTES, MAX_ENTRIES)
    entries = []
    for i in range(n):
        u = struct.unpack('>%dH' % U16_PER_ENTRY, data[i*ENTRY_BYTES:(i+1)*ENTRY_BYTES])
        entries.append(u)
    return sha, entries


def main():
    ap = argparse.ArgumentParser(description="Dump chan_tuning_2069rev4 per-channel radio writes.")
    ap.add_argument('elf')
    ap.add_argument('outdir')
    ap.add_argument('--min-freq', type=int, default=FIVE_G_MIN_FREQ,
                    help="emit channels with freq >= this (default 5170 = ch34)")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    sha, entries = read_table(a.elf)
    src = os.path.basename(a.elf)

    sel = [u for u in entries if u[1] >= a.min_freq]
    sel.sort(key=lambda u: u[1])

    offs = sorted(CLUSTER1_MAP)
    c = open(os.path.join(a.outdir, 'chan_tuning_2069rev4_5g.c'), 'w')
    m = open(os.path.join(a.outdir, 'chan_tuning_2069rev4_5g.md'), 'w')

    c.write(f"/* Autogenerated by extract_chan_tuning_2069rev4.py\n"
            f" * Source: {src} (sha256:{sha})\n"
            f" * Table: {SYM} (radio 2069 rev4 — the DSL-3580L variant)\n"
            f" * {len(sel)} 5 GHz channels (freq >= {a.min_freq} MHz, i.e. ch 34 and up).\n"
            f" */\n\n")

    c.write("static const u16 chan_2069rev4_cluster1_regs[45] = {\n\t")
    c.write(', '.join(f"0x{CLUSTER1_MAP[o]:04x}" for o in offs))
    c.write("\n};\n\n")

    c.write("struct chan_2069rev4 {\n\tu16 chan;\n\tu16 freq;\n"
            "\tu16 val[45];   /* parallel to chan_2069rev4_cluster1_regs */\n"
            "\tu16 raw_tail[11]; /* off 94..114, reg targets TODO */\n};\n\n")
    c.write(f"static const struct chan_2069rev4 chan_2069rev4_5g[{len(sel)}] = {{\n")
    for u in sel:
        vals = ', '.join(f"0x{u[o//2]:04x}" for o in offs)
        tail = ', '.join(f"0x{u[o//2]:04x}" for o in TAIL_OFFS)
        c.write(f"\t{{ {u[0]:>3}, {u[1]}, "
                f"{{ {vals} }}, {{ {tail} }} }},\n")
    c.write("};\n")
    c.close()

    m.write(f"# chan_tuning_2069rev4 — per-channel radio tuning (5 GHz, ch >= 34)\n\n")
    m.write(f"Source: `{src}` (sha256 `{sha[:16]}...`). Table `{SYM}` "
            f"(radio 2069 **rev4**, the DSL-3580L variant"
    m.write(f"Entry = 58 u16: `[0]`=channel, `[1]`=freq(MHz), `[2..57]`=56 radio "
            f"raw values. {len(sel)} channels at freq >= {a.min_freq} MHz.\n\n")
    m.write("Each channel below: the 45 **cluster1** writes "
            "values (off 94..114) are listed raw.\n\n")
    for u in sel:
        m.write(f"## ch {u[0]} ({u[1]} MHz)\n\n```\n")
        for o in offs:
            m.write(f"radio[0x{CLUSTER1_MAP[o]:04x}] <- 0x{u[o//2]:04x}\n")
        m.write("# rev4 tail (reg TODO): " +
                ' '.join(f"0x{u[o//2]:04x}" for o in TAIL_OFFS) + "\n```\n\n")
    m.close()
    # --- b43 porting table: emit the b43_chantab_r2069[] rows directly ---
    # radio_raw[k] = entry off (4+2k) = val[k], k=0..38 (cluster1 writes 0..38)
    # bw1..bw6     = entry off 82..92 = val[39..44]
    b = open(os.path.join(a.outdir, 'b43_chantab_r2069_rev4.inc'), 'w')
    b.write(f"/* Autogenerated by extract_chan_tuning_2069rev4.py --emit-b43\n"
            f" * Source: {src} (sha256:{sha})\n"
            f" * chan_tuning_2069rev4, 5 GHz ch>=34 ({len(sel)} channels).\n"
            f" * radio_raw[0..38] = cluster1 off 4..80 (radio); chan_raw6 = off 82..92\n"
            f" * Register targets: chan_2069rev4_cluster1_regs[] / r2069_chan_writes[].\n */\n")
    for u in sel:
        raw = [u[o // 2] for o in offs]           # 45 cluster1 values, off 4..92
        radio_raw, chan_raw6 = raw[:39], raw[39:]
        phy_bw = u[52:58]                          # off 104..114: VERI PHY 0x371..0x376
        b.write(f"\t{{ /* chan {u[0]:>3}, {u[1]} MHz */\n"
                f"\t\t.channel = {u[0]},\n\t\t.freq    = {u[1]},\n"
                f"\t\t.radio_raw = {{\n")
        for i in range(0, 39, 6):
            b.write("\t\t\t" + ", ".join(f"0x{v:04x}" for v in radio_raw[i:i+6]) + ",\n")
        b.write("\t\t},\n"
                "\t\t.chan_raw6 = { " + ", ".join(f"0x{v:04x}" for v in chan_raw6) + " },\n"
                "\t\t.phy_bw    = { " + ", ".join(f"0x{v:04x}" for v in phy_bw) + " },\n"
                "\t},\n")
    b.close()
    print(f"# wrote {a.outdir}/chan_tuning_2069rev4_5g.c and .md "
          f"({len(sel)} channels)")
    print(f"# wrote {a.outdir}/b43_chantab_r2069_rev4.inc")


if __name__ == '__main__':
    main()
